<?xml version="1.0"?>
<!-- <robot name="gurdy"> -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gurdy">

<!--You will also need the dimensions of the the basic geometry to have some idea of the way that everything is connected, and the collision elements geometry:-->
<!--For base_link there is no inertia needed because its a non-functional element-->

<!--base_link :         box size="0.01 0.01 0.01"                   mass=None, --> 
<!--head_link :         cylinder radius="0.05"      length="0.04"   mass value="0.01"-->
<!--upper_leg_links :   cylinder radius="0.0025"    length="0.06"   mass value="0.01"-->
<!--lower_leg_links :   cylinder radius="0.0015"    length="0.06"   mass value="0.01"-->
<!--foot_links :        sphere   radius="0.008"                     mass value="0.01"-->

<!--Friction is vital in the foot links. Try different values and see the effect on locomotion. These are some orientative values:-->
<!--kp = 1000.0-->
<!--kd = 1000.0-->
<!--mu1 = 10.0-->
<!--mu2 = 10.0-->

<!--PID are tricky. Use rqt_reconfigure to get correct values. These are some orientative values:-->
<!--{p: 3.0, i: 1.0, d: 0.0}-->

<!-- ################### XACRO Definitions ############################# -->
<!-- ################### XACRO Definitions ############################# -->
<!-- ################### XACRO Definitions ############################# -->
<!-- ################### XACRO Definitions ############################# -->
<!-- ################### XACRO Definitions ############################# -->

<!-- MUST ALWAYS GO BEFORE XACRO DEFINITIONS -->
<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/gurdy</robotNamespace>
    </plugin>
</gazebo>

<!-- You can perform the basic operations (+,-,*,/), the unary minus, and use parenthesis. This allows you to, for example, calculate the inertias based on the dimensions directly in the XACRO file. -->
<xacro:property name="head_ixx" value="${( (m/12.0) * (3*head_radius*head_radius + head_length*head_length) )}"/>
<!-- Another example would be symmetrically-positioned links or joints. -->
<xacro:property name="head_iyy" value="${head_ixx}"/>
<xacro:property name="head_izz" value="( (m*head_radius*head_radius) / (2.0) )"/>

<xacro:property name="m" value="0.01"/>
<xacro:property name="head_radius" value="0.05"/>
<xacro:property name="head_length" value="0.04"/>
<xacro:property name="head_z_origin" value="0.02"/>

<!-- MACROS
This is by far the most useful feature of XACROS. There are two main types of MACROS: -->
<!-- SIMPLE MACRO -->
<xacro:macro name="default_origin">
    <origin xyz="0 0 0" rpy="0 0 0"/>
</xacro:macro>
<xacro:macro name="visual_origin">
    <xacro:default_origin/>
</xacro:macro>


<!--######################## UPPER LEG ########################-->
<xacro:property name="upper_leg_radius" value="0.0025"/>
<xacro:property name="upper_leg_length" value="0.06"/>
<xacro:macro name="upper_leg_origin">
    <origin xyz="0 0 0.02" rpy="0 0 0"/> <!--UPPER-->
</xacro:macro>
<xacro:macro name="upper_leg_link_inertia">
    <!-- ORIGINAL value taken from Inertial_calculator.py -->
    <!-- <inertia ixx="3.015625e-06" ixy="0.0" ixz="0.0" iyy="3.015625e-06" iyz="0.0" izz="3.125e-08"/> -->
    <!-- SOLUTION INERTIA ++++ WAY LESS TWITCHING -->
    <inertia ixx="3.015625e-05" ixy="0.0" ixz="0.0" iyy="3.015625e-05" iyz="0.0" izz="3.125e-07"/>
</xacro:macro>


<!-- PARAMETERISED MACRO -->
<xacro:macro name="generate_upper_leg_link" params="num">
    <link name="upper_leg_M${num}_link"><!--UPPER-->
        <inertial>
            <xacro:upper_leg_origin/>
            <mass value="${m}"/>
            <xacro:upper_leg_link_inertia/>
        </inertial>
        <collision>
            <xacro:upper_leg_origin/>
            <geometry>
                <cylinder radius="${upper_leg_radius}" length="${upper_leg_length}"/>
            </geometry>
        </collision>
        <visual>
            <xacro:visual_origin/>
            <geometry>
                <mesh filename="package://gurdy_description/models/gurdy/meshes/gurdy_higherleg_v2.dae"/>
            </geometry>
        </visual>
    </link>
</xacro:macro>



<!--######################## LOWER LEG ########################-->
<xacro:property name="lower_leg_radius" value="0.0015"/>
<xacro:property name="lower_leg_length" value="0.06"/>
<xacro:macro name="lower_leg_origin">
    <origin xyz="0 0 0.03" rpy="0 0 0"/> <!--LOWER-->
</xacro:macro>
<xacro:macro name="lower_leg_link_inertia">
    <!-- ORIGINAL value taken from Inertial_calculator.py -->
    <!-- <inertia ixx="3.005625e-06" ixy="0.0" ixz="0.0" iyy="3.005625e-06" iyz="0.0" izz="1.125e-08"/> -->
    <!-- SOLUTION INERTIA ++++  -->
    <inertia ixx="3.005625e-05" ixy="0.0" ixz="0.0" iyy="3.005625e-05" iyz="0.0" izz="1.125e-07"/>
</xacro:macro>

<!-- PARAMETERISED MACRO -->
<xacro:macro name="generate_lower_leg_link" params="num">
    <link name="lower_leg_M${num}_link"><!--UPPER-->
        <inertial>
            <xacro:lower_leg_origin/>
            <mass value="${m}"/>
            <xacro:lower_leg_link_inertia/>
        </inertial>
        <collision>
            <xacro:lower_leg_origin/>
            <geometry>
                <cylinder radius="${lower_leg_radius}" length="${lower_leg_length}"/>
            </geometry>
        </collision>
        <visual>
            <xacro:visual_origin/>
            <geometry>
                <mesh filename="package://gurdy_description/models/gurdy/meshes/gurdy_lowerleg_v2.dae"/>
            </geometry>
        </visual>
    </link>
</xacro:macro>


<!--######################## FOOT ########################-->
<xacro:property name="foot_radius" value="0.008"/>
<xacro:macro name="foot_origin">
    <origin xyz="0 0 0.01" rpy="0 0 0"/> <!--FOOT-->
</xacro:macro>
<xacro:macro name="foot_link_inertia">
    <!-- ORIGINAL value taken from Inertial_calculator.py -->
    <!-- <inertia ixx="2.56e-07" ixy="0.0" ixz="0.0" iyy="2.56e-07" iyz="0.0" izz="2.56e-07"/> -->
    <!-- SOLUTION INERTIA ++++  -->
    <inertia ixx="1.28e-06" ixy="0.0" ixz="0.0" iyy="1.28e-06" iyz="0.0" izz="1.28e-06"/>
</xacro:macro>

<!-- PARAMETERISED MACRO -->
<xacro:macro name="generate_foot_link" params="num">
    <link name="foot_M${num}_link"><!--UPPER-->
        <inertial>
            <xacro:foot_origin/>
            <mass value="${m}"/>
            <xacro:foot_link_inertia/>
        </inertial>
        <collision>
            <xacro:foot_origin/>
            <geometry>
                <sphere radius="${foot_radius}"/>
            </geometry>
        </collision>
        <visual>
            <xacro:visual_origin/>
            <geometry>
                <sphere radius="${foot_radius}"/>
            </geometry>
        </visual>
    </link>
</xacro:macro>

<!-- <xacro:macro name="generate_transmission" params="parent_link child_link link_num" >
    <transmission name="transmission_${parent_link}_${child_link}${link_num}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${parent_link}_${child_link}_joint">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_${parent_link}_${child_link}">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
</xacro:macro>

<xacro:generate_transmission parent_link=""> -->




<!-- ################### LINK Definitions ############################# -->
<!-- ################### LINK Definitions ############################# -->
<!-- ################### LINK Definitions ############################# -->
<!-- ################### LINK Definitions ############################# -->
<!-- ################### LINK Definitions ############################# -->


    <link name="base_link">
        <!--<inertial>-->
        <!--    <origin/>-->
        <!--    <mass value="0.001"/>-->
        <!--    <inertia ixx="1.66666666667e-08" ixy="0.0" ixz="0.0" iyy="1.66666666667e-08" iyz="0.0" izz="1.66666666667e-08"/>-->
        <!--</inertial>-->
        <collision>
            <xacro:default_origin/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>
        <visual>
            <xacro:visual_origin/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
    </link>
    
            <link name="head_link">
                <inertial>
                    <origin xyz="0 0 ${head_z_origin}" rpy="0 0 0"/>
                    <mass value="${m}"/>
                    <!-- <inertia ixx="7.58333333333e-06" ixy="0.0" ixz="0.0" iyy="7.58333333333e-06" iyz="0.0" izz="1.25e-05"/> -->
                    <inertia ixx="${head_ixx}" ixy="0.0" ixz="0.0" iyy="head_iyy" iyz="0.0" izz="head_izz"/>
                </inertial>
                <collision>
                    <origin xyz="0 0 ${head_z_origin}" rpy="0 0 0"/>
                    <geometry>
                        <cylinder radius="${head_radius}" length="${head_length}"/>
                        <!-- <mesh filename="package://gurdy_description/models/gurdy/meshes/gurdy_head_v2.dae"/> -->
                    </geometry>
                </collision>
                <visual>
                    <xacro:visual_origin/>
                    <geometry>
                        <mesh filename="package://gurdy_description/models/gurdy/meshes/gurdy_head_v2.dae"/>
                    </geometry>
                </visual>
            </link>

                    <xacro:generate_upper_leg_link num="1" />
                    <xacro:generate_upper_leg_link num="2" />
                    <xacro:generate_upper_leg_link num="3" />
    

                            <xacro:generate_lower_leg_link num="1" />
                            <xacro:generate_lower_leg_link num="2" />
                            <xacro:generate_lower_leg_link num="3" />

                    
    
                                    <xacro:generate_foot_link num="1" />
                                    <xacro:generate_foot_link num="2" />
                                    <xacro:generate_foot_link num="3" />
    
                                        



<!-- ################### JOINT Definitions ############################# -->
<!-- ################### JOINT Definitions ############################# -->
<!-- ################### JOINT Definitions ############################# -->
<!-- ################### JOINT Definitions ############################# -->
<!-- ################### JOINT Definitions ############################# -->

    <joint name="base_head_joint" type="fixed">
        <parent link="base_link"/>
        <child link="head_link"/>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <!--Rest NOT NEEDED for FIXED joint-->
        <!--<limit lower="-0.2" upper="0.2" effort="1.0" velocity="0.005"/>-->
        <!--<axis xyz="0 0 0"/>-->
    </joint>
    
            <joint name="head_upper_legM1_joint" type="revolute">
                <parent link="head_link"/>
                <child link="upper_leg_M1_link"/>
                <!--this is the Pitch value from the urdf to graphiz map pdf-->
                <!--<origin xyz="-0.02165 -0.0125 -0.008" rpy="3.14159 -1.05879e-22 0.523599"/>-->
                <!--This Pitch value is from solution-->
                <!--Haven't seen a difference-->
                <origin xyz="-0.02165 -0.0125 -0.008" rpy="3.14159 0 0.523599"/>
                <!--Rest NOT NEEDED for FIXED joint-->
                <limit lower="-1.57" upper="0.0" effort="1.0" velocity="0.005"/>
                <axis xyz="0 1 0"/>
            </joint>
            
            <joint name="head_upper_legM2_joint" type="revolute">
                <parent link="head_link"/>
                <child link="upper_leg_M2_link"/>
                <origin xyz="0.02165 -0.0125 -0.008" rpy="3.14159 0 2.61799"/>
                <!--Rest NOT NEEDED for FIXED joint-->
                <limit lower="-1.57" upper="0.0" effort="1.0" velocity="0.005"/>
                <axis xyz="0 1 0"/>
            </joint>
            
            <joint name="head_upper_legM3_joint" type="revolute">
                <parent link="head_link"/>
                <child link="upper_leg_M3_link"/>
                <origin xyz="0 0.025 -0.008" rpy="3.14159 0 -1.5708"/>
                <!--Rest NOT NEEDED for FIXED joint-->
                <limit lower="-1.57" upper="0.0" effort="1.0" velocity="0.005"/>
                <axis xyz="0 1 0"/>
            </joint>
            
                    <joint name="upper_legM1_lowerlegM1_joint" type="revolute">
                        <parent link="upper_leg_M1_link"/>
                        <child link="lowerleg_M1_link"/>
                        <origin xyz="0 0.0095 0.06" rpy="0 0 3.14159"/>
                        <limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>
                        <axis xyz="0 1 0"/>
                    </joint>
                    
                    <joint name="upper_legM2_lowerlegM2_joint" type="revolute">
                        <parent link="upper_leg_M2_link"/>
                        <child link="lowerleg_M2_link"/>
                        <origin xyz="0 0.0095 0.06" rpy="0 0 3.14159"/>
                        <limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>
                        <axis xyz="0 1 0"/>
                    </joint>
                    
                    <joint name="upper_legM3_lowerlegM3_joint" type="revolute">
                        <parent link="upper_leg_M3_link"/>
                        <child link="lowerleg_M3_link"/>
                        <origin xyz="0 0.0095 0.06" rpy="0 0 3.14159"/>
                        <limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>
                        <axis xyz="0 1 0"/>
                    </joint>
                    
                            <joint name="basefoot_peg_M1_basefoot_peg_M1_joint_joint" type="fixed">
                                <parent link="lowerleg_M1_link"/>
                                <child link="footM1_link"/>
                                <origin xyz="0 0 0.06" rpy="0 0 0"/>
                                <!--Rest NOT NEEDED for FIXED joint-->
                                <!--<limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>-->
                                <!--<axis xyz="0 1 0"/>-->
                            </joint>
                            
                            <joint name="basefoot_peg_M2_basefoot_peg_M2_joint_joint" type="fixed">
                                <parent link="lowerleg_M2_link"/>
                                <child link="footM2_link"/>
                                <origin xyz="0 0 0.06" rpy="0 0 0"/>
                                <!--Rest NOT NEEDED for FIXED joint-->
                                <!--<limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>-->
                                <!--<axis xyz="0 1 0"/>-->
                            </joint>
                            
                            <joint name="basefoot_peg_M3_basefoot_peg_M3_joint_joint" type="fixed">
                                <parent link="lowerleg_M3_link"/>
                                <child link="footM3_link"/>
                                <origin xyz="0 0 0.06" rpy="0 0 0"/>
                                <!--Rest NOT NEEDED for FIXED joint-->
                                <!--<limit lower="-2.65" upper="0" effort="1.0" velocity="0.005"/>-->
                                <!--<axis xyz="0 1 0"/>-->
                            </joint>




    
<!-- ################### TRANSMISSION Definitions ############################# -->
<!-- ################### TRANSMISSION Definitions ############################# -->
<!-- ################### TRANSMISSION Definitions ############################# -->
<!-- ################### TRANSMISSION Definitions ############################# -->
<!-- ################### TRANSMISSION Definitions ############################# -->

    

            <transmission name="transmission_head_upper_legM1">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="head_upper_legM1_joint">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                </joint>
                <actuator name="motor_head_upper_legM1">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission>

            <transmission name="transmission_head_upper_legM2">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="head_upper_legM2_joint">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                </joint>
                <actuator name="motor_head_upper_legM2">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission>

            <transmission name="transmission_head_upper_legM3">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="head_upper_legM3_joint">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                </joint>
                <actuator name="motor_head_upper_legM3">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission>

                    <transmission name="transmission_upper_legM1_lowerlegM1">
                        <type>transmission_interface/SimpleTransmission</type>
                        <joint name="upper_legM1_lowerlegM1_joint">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                        </joint>
                        <actuator name="motor_upper_legM1_lowerlegM1">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                            <mechanicalReduction>1</mechanicalReduction>
                        </actuator>
                    </transmission>

                    <transmission name="transmission_upper_legM2_lowerlegM2">
                        <type>transmission_interface/SimpleTransmission</type>
                        <joint name="upper_legM2_lowerlegM2_joint">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                        </joint>
                        <actuator name="motor_upper_legM2_lowerlegM2">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                            <mechanicalReduction>1</mechanicalReduction>
                        </actuator>
                    </transmission>

                    <transmission name="transmission_upper_legM3_lowerlegM3">
                        <type>transmission_interface/SimpleTransmission</type>
                        <joint name="upper_legM3_lowerlegM3_joint">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                        </joint>
                        <actuator name="motor_upper_legM3_lowerlegM3">
                            <hardwareInterface>EffortJointInterface</hardwareInterface>
                            <mechanicalReduction>1</mechanicalReduction>
                        </actuator>
                    </transmission>

    


    
<!-- ################### MATERIALS Definitions ############################# -->
<!-- ################### MATERIALS Definitions ############################# -->
<!-- ################### MATERIALS Definitions ############################# -->
<!-- ################### MATERIALS Definitions ############################# -->
<!-- ################### MATERIALS Definitions ############################# -->

        <gazebo reference="head_link">
            <mu1>10.0</mu1>
            <mu2>10.0</mu2>
        </gazebo>
                            <!-- This is for color and physical properties in Gazebo, color won't work with the material tag in gazebo
                            only for URDF coloring -->
                            <gazebo reference="footM1_link">
                                <kp>1000.0</kp>
                                <kd>1000.0</kd>
                                <mu1>10.0</mu1>
                                <mu2>10.0</mu2>
                                <!--<material>Gazebo/Red</material>-->
                                <material>Gazebo/White</material>
                            </gazebo>
                            
                            <!-- This is for color and physical properties in Gazebo, color won't work with the material tag in gazebo
                            only for URDF coloring -->
                            <gazebo reference="footM2_link">
                                <kp>1000.0</kp>
                                <kd>1000.0</kd>
                                <mu1>10.0</mu1>
                                <mu2>10.0</mu2>
                                <!--<material>Gazebo/Green</material>-->
                                <material>Gazebo/White</material>
                            </gazebo>
                            
                            <!-- This is for color and physical properties in Gazebo, color won't work with the material tag in gazebo
                            only for URDF coloring -->
                            <gazebo reference="footM3_link">
                                <kp>1000.0</kp>
                                <kd>1000.0</kd>
                                <mu1>10.0</mu1>
                                <mu2>10.0</mu2>
                                <!--<material>Gazebo/Blue</material>-->
                                <material>Gazebo/White</material>
                            </gazebo>

<!-- ################### SENSOR Definitions ############################# -->
<!-- ################### SENSOR Definitions ############################# -->
<!-- ################### SENSOR Definitions ############################# -->
<!-- ################### SENSOR Definitions ############################# -->
<!-- ################### SENSOR Definitions ############################# -->

    <gazebo>
        <plugin name="gazebo_ros_imu_controller" filename="libgazebo_ros_imu.so">
            <robotNamespace>/gurdy</robotNamespace>
            <topicName>imu/data</topicName>
            <serviceName>imu/service</serviceName>
            <bodyName>base_link</bodyName>
            <gaussianNoise>0</gaussianNoise>
            <rpyOffsets>0 0 0</rpyOffsets>
            <updateRate>10.0</updateRate>
            <alwaysOn>true</alwaysOn>
            <gaussianNoise>0</gaussianNoise>
        </plugin>
</gazebo>


    
    
    
</robot>
        
