mira:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
    
    # The name of the controller is recommended to have the exact same joint name, proceeded by "_position_controller"
    # Position Controllers ---------------------------------------
    roll_joint_position_controller:
        # Then, you select the type, which we recommend as the JointPositionController because we want to control it through the position of the joints.
        type: effort_controllers/JointPositionController
        # The JointName: This is linking the joint to the controller.
        joint: roll_joint
        # Sets the PID values. This is absolutely vital to making the actuators reach the desired position without oscillations or going too slow.
        pid: {p: 1.0, i: 1.0, d: 0.0}
        
    pitch_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: pitch_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}
        
    yaw_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: yaw_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}
    
    # To add more just add them here as the first one